layout_spectrum: 0.4426183
typography_spectrum: 0.6339093
color:
  saturation: 0.1543015
  lightness: 0.386135
  brandStrength: 0.564415
  rhythmicContrast: 0.4703664
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: There Company
